// Generated by CoffeeScript 1.4.0
(function() {
  var K, binding, editFile, element, url, _i, _len, _ref;

  K = KeyboardJS;

  K.on("e", function() {
    return editFile("index.html");
  });

  K.on("r", function() {
    return window.location.reload();
  });

  _ref = document.querySelectorAll("a[kb]");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    element = _ref[_i];
    binding = element.attributes['kb'].value;
    url = element.attributes['href'].value;
    K.on(binding, (function() {
      return window.location = this;
    }).bind(url));
  }

  editFile = function(file) {
    var r;
    r = new XMLHttpRequest();
    r.open("POST", "/files/" + file);
    r.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    return r.send("");
  };

}).call(this);
