#!/bin/bash
# ------------------------------------------------------------------------------
# ALIASES AND FUNCTIONS
#

source ~/.config-base/bash/common


# dl takes an URL as its argument and downloads it using the server supplied
# file name to PWD.
dl() {
  curl -O -L "$@"
}

# h displayes the bash history with fuzzy match/select.
# NOTE: h relies on a bunch of tools being installed.
h() {
  local line=''
  line="$(history | selectline)"
  line=$(echo $line | python -c "import sys;[sys.stdout.write(' '.join(line.split(' ')[:1])) for line in sys.stdin]")
  line=$(history -p !$line)
  if [[ "$line" !=  "!" ]]; then
    if [ -n "$DISPLAY" ] && [ $(which xdotool) ] && [ $(which xsel) ] ; then
      echo -n $line | xsel --clipboard
      ( # this subshell silences job info output
        ( # this subshell is the background job
          sleep 0.4
          xdotool keydown ctrl key v keyup ctrl 2>/dev/null
        ) &
      )
    elif [ $(which pbcopy) ]; then
      echo -n $line | pbcopy
    else
      echo $line
    fi
  fi
}

alias df='df -h -T'

__exec_in_dir() {
  local ncolors=$(tput colors)
  if test -n "$ncolors" && test $ncolors -ge 8; then
    local reset="$(tput sgr0)"
    local red="$(tput setaf 1)"
    local gre="$(tput setaf 2)"
    local yel="$(tput setaf 3)"
    local mag="$(tput setaf 5)"
  fi

  local dir="${1}"
  [[ -d ${dir} ]] || return 0
  shift
  local args="${*}"
  (
    cd "${dir}"
    local d=$(basename "${PWD}")
    echo ''
    echo "$yel ---- $red [ $mag $d $red ] $yel ---- $reset"
    ${args}
    echo ''
  )
}
export -f __exec_in_dir

indirs() {
  [[ -n $* ]] \
    && find \
         -L . \
         -mindepth 1 \
         -maxdepth 1 \
         -type d \
         -execdir bash -e -c \
         "__exec_in_dir '{}' ${*}" \;
}

__exec_in_git_dir() {
  local ncolors=$(tput colors)
  if test -n "$ncolors" && test $ncolors -ge 8; then
    local reset="$(tput sgr0)"
    local red="$(tput setaf 1)"
    local gre="$(tput setaf 2)"
    local yel="$(tput setaf 3)"
    local mag="$(tput setaf 5)"
  fi
  local dir="${1%%.git}"
  [[ -d ${dir} ]] || return 0
  shift
  local args="${*}"
  (
    cd "${dir}"
    command git rev-parse 2> /dev/null || return 0
    echo ''
    echo "$red [ $mag $PWD $red ] $yel ---- $reset"
    ${args}
    echo ''
  )
}
export -f __exec_in_git_dir

ingitdirs() {
  [[ -n $* ]] \
    && find \
         -L . \
         -name .git \
         -execdir bash -e -c \
         "__exec_in_git_dir '{}' ${*}" \;
}

mgall() {
  local dirs=""
  for dir in $(find -L . -name .git -execdir dirname {} \;); do
    dirs=$dirs$(builtin cd $dir && command git rev-parse 2>/dev/null && [[ ! $(command git status --porcelain) = "" ]] && echo -n " $dir" )
  done
  if [ -n "$dirs" ]; then
    magit ${dirs}
  else
    echo "no uncommited"
  fi

}

rmosx() {
  echo -n "recursivley delete all __MACOSX, .DS_Store files?"
  read -n 1 yorn;
  if test "$yorn" = "y"; then
    echo
    find . \
         -name __MACOSX -type d -execdir rm -r {} \; -prune  \
         -o \( -name .DS_Store -type f -execdir rm {} \; -prune \)
  else
    echo
    return 1
  fi
}

rmclean() {
  echo -n "Really clean $(pwd)?"
  read -n 1 yorn;
  if test "$yorn" = "y"; then
    echo
    rm -f \#* *~ .*~ *.bak .*.bak  *.tmp .*.tmp core a.out;
  else
    echo
    return 1
  fi
}

rmpyc() {
  echo -n "recursivley delete all .pyc files?"
  read -n 1 yorn;
  if test "$yorn" = "y"; then
    echo
    find -name \*.pyc -execdir rm '{}' \;
  else
    echo
    return 1
  fi
}

bak() {
  if [[ -e $1 ]]; then
    cp "$1" "$1.backup-$(date +"%m-%d-%Y_%H%M%S")"
  else
    return 1
  fi
}

bakdir() {
  if [[ -d $1 ]]; then
    cp -R "$1" "$1.backup-$(date +"%m-%d-%Y_%H%M%S")"
  else
    return 1
  fi
}

bakmv() {
  if [[ -e $1 ]]; then
    mv "$1" "$1.backup-$(date +"%m-%d-%Y_%H%M%S")"
  else
    return 1
  fi
}

wsdir-set() {
  [[ $(which wsname) ]] || return 0
  if [[ $(wsname -p) ]]; then
    mkdir -p ~/.config/wsdirs/
    echo -ne $PWD > ~/.config/wsdirs/$(wsname -p)
  fi
}

wsdir-unset() {
  [[ $(which wsname) ]] || return 0
  if [[ $(wsname -p) ]]; then
    rm -f ~/.config/wsdirs/$(wsname -p)
  fi
}

wsdir-cd() {
  [[ $(which wsname) ]] || return 0
  local wsnamep=$(wsname -p)
  if [ -f ~/.config/wsdirs/$wsnamep ]; then
    cd $(cat ~/.config/wsdirs/$wsnamep)
  else
    return 1
  fi
}

wsdir-get() {
  [[ $(which wsname) ]] || return 0
  local wsnamep=$(wsname -p)
  if [ -f ~/.config/wsdirs/$wsnamep ]; then
    echo -ne $(cat ~/.config/wsdirs/$wsnamep)
  else
    return 1
  fi
}

wsenv-edit() {
  [[ $(which wsname) ]] || return 0
  local wsnamep=""
  if  [[ $(which wsname) ]] && [[ $(wsname -p) ]]; then
    if [[ $(wsdir-get) ]]; then
      wsnamep=$(basename $(wsdir-get))
    else
      wsnamep=$(wsname -p)
    fi
    mkdir -p ~/.config/wsenv/
    e "~/.config/wsenv/$wsnamep"
  fi
}

wsenv-source() {
  [[ $(which wsname) ]] || return 0
  local wsnamep=""
  if [[ $(wsname -p) ]]; then
    if [[ $(wsdir-get) ]]; then
      wsnamep=$(basename $(wsdir-get))
    else
      wsnamep=$(wsname -p)
    fi
    if [ -f ~/.config/wsenv/$wsnamep ]; then
      . "${HOME}/.config/wsenv/$wsnamep"
    else
      return 1
    fi
  fi
}

awscredentials() {
  local account="aws-$1"
  local access_key=$(acc ${account} access-key-id)
  local access_key_secret=$(acc ${account} secret-access-key)
  local url=$(acc ${account} ec2-url)
  export AWS_ACCESS_KEY_ID=$access_key
  export AWS_SECRET_ACCESS_KEY=$access_key_secret
  export AWS_ACCESS_KEY=$access_key
  export AWS_SECRET_KEY=$access_key_secret
  export EC2_URL=$url
  echo " $access_key : $access_key_secret : $url"
}

eless() {
  zless $(which ${1})
}

alias j="jobs -l"
if [ ${__OS} = darwin ]; then
  alias ls="ls -G"
else
  alias ls="ls --group-directories-first --color"
fi

l() {
  if [ $(which pls) ] && [ ! ${__OS} = darwin ]; then
    pls "$@"
  else
    ls -l "$@"
  fi
}

alias la='ls -A'
alias ll="ls -l"
alias lsg="git ls-dir"
alias lslistenports="sudo netstat -plunt"
alias adblogcat="adb logcat | adb-logcat-pp"

lsnew() {
  find . \
       -mindepth 1 \
       -maxdepth ${1:-1} \
       -not \( -type d -name ".git" -prune \) \
       -not \( -type d -name ".avfs" -prune \) \
       -type f \
       -mtime 0 \
       -printf '%Tm-%Td %TH:%TM  %P\n' \
    | sort
}

fadb-uninstall() {
  local selected=$(adb shell 'pm list packages -f' | sed -e 's/.*=//' | sort | fzf)
  [[ -z $selected ]] && return 1
  adb shell pm uninstall $selected
}

fadb-install() {
  local selected
  selected=$(find -type f -iname '*.apk' | fzf)
  [[ -z $selected ]] && return 1
  adb install -r $selected
}

fadb-start-apk() {
  local selected;
  selected=$(find -type f -iname '*.apk' | fzf)
  [[ -z $selected ]] && return 1
  local pkg=$(aapt dump badging $selected|awk -F" " '/package/ {print $2}'|awk -F"'" '/name=/ {print $2}')
  local act=$(aapt dump badging $selected|awk -F" " '/launchable-activity/ {print $2}'|awk -F"'" '/name=/ {print $2}')
  adb shell am start -n $pkg/$act
}

__select_subdir() {
  local query="$@"
  local result=$(find . -mindepth 1 -maxdepth 10 -type d \
                      -not \( -name ".?*" -prune \) \
                      -not \( -name "node_modules" -prune \) \
                      -not \( -name "Godeps" -prune \) \
                    | cut -c 3- | selectline --query="$query")
  [[ -z $result ]] && return 1
  echo -n "./${result}"
}


function findupcased {
  find . -name '*[A-Z]*'
}

function findext {
  [[ -z $1 ]] && return 1
  find . -iname \*.${1}
}

alias fe='findext'

function findname {
  [[ -z $1 ]] && return 1
  find . -iname \*${1}\*
}
alias fn='findname'

# cdup maches upwards the path and sets PWD to the first partial match.
function cdup {

  if [ $# == 0 ]; then
    cd ..
    return 0
  fi

  local dir="$1"
  local old=`pwd`

  # Try matching the full segment in path name
  local new=`perl -pe "s{(.*/\Q$dir\E)(?=/|$).*?$}{\1};" <<< $old`

  # If failed, try partial match of segment
  if [ "$old" == "$new" ]; then
    new=`perl -pe "s{(.*/[^/]*?\Q$dir\E[^/]*?)(?=/|$).*?$}{\1}" <<< $old`
  fi

  # No replacements done, so we failed
  if [ "$old" == "$new" ]; then
    echo "Can't find '$dir' among ancestor directories ($old == $new)." 1>&2
    return 1
  fi

  cd $new
}

function cdl {
  local target
  target=`resolvelink $PWD`
  [[ -z $target ]] && return 1
  cd $target
}

alias c="cd"
alias u="cdup"

alias t2='tree -d -L 2'
alias t3='tree -d -L 3'

alias p='python'
alias doco='docker-compose'
alias dkr='docker'

alias agent='eval $(ssh-agent); ssh-add;'

agentunset() {
  unset SSH_AUTH_SOCK
  unset SSH_AGENT_PID
}

# Start gnupg or ssh agent
agentGpg(){
  rm -f ~/.ssh/control:*
  agent_file="$HOME/.gnupg/gpg-agent-info-$(hostname)"
  unset GPG_AGENT_INFO; unset SSH_AUTH_SOCK; unset SSH_AGENT_PID
  rm -f "${agent_file}"
  eval $(gpg-agent --daemon --sh --enable-ssh-support --write-env-file=${agent_file})
  export GPG_AGENT_INFO
  export SSH_AUTH_SOCK
  export SSH_AGENT_PID
}

alias apt-update-upgrade='sudo apt-get update && sudo apt-get dist-upgrade'

# ffmpeg - for - phone
# ffmpeg-for-phone() {
#   for A in $@; do ffmpeg -i ${A} -s qvga -vcodec mpeg4 -acodec libfaac ${A}.mp4 ;done
# }

# Extract wrapper for a number of archive formats
ex () {
  if [[ -f $1 ]]; then
    case $1 in
      *.tar.bz2)           tar xjf $1     ;;
      *.tar.gz)            tar xzf $1     ;;
      *.tar)               tar xf $1      ;;
      *.tgz)               tar xf $1      ;;
      *.bz2)               bunzip2 $1     ;;
      *.rar)               unrar x $1     ;;
      *.gz)                gunzip $1      ;;
      *.lzma)              unxz $1        ;;
      *.rpm)               bsdtar xf $1   ;;
      *.zip)               unzip $1       ;;
      *.Z)                 uncompress $1  ;;
      *.7z)                7z x $1        ;;
      *.exe)               cabextract $1  ;;
      *)                   echo "'$1': unrecognized file compression" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Make directory and change to it
mkcd() {
  [[ $1 ]] || return 0
  [[ ! -d $1 ]] && mkdir -vp "$1"
  [[ -d $1 ]] && builtin cd "$1"
}

# Change directory to homesync directory
[[ -d ~/.config/dotfiles ]] && alias cdhs='builtin cd ~/.config/dotfiles'

# Disk usage - recursive for each child folder
dudir() {
  du -sk ./* | sort -n | awk 'BEGIN{ pref[1]="K"; pref[2]="M"; pref[3]="G";} { total = total + $1; x = $1; y = 1; while( x > 1024 ) { x = (x + 1023)/1024; y++; } printf("%g%s\t%s\n",int(x*10)/10,pref[y],$2); } END { y = 1; while( total > 1024 ) { total = (total + 1023)/1024; y++; } printf("Total: %g%s\n",int(total*10)/10,pref[y]); }'
}

# z workspace prefix name
cdd() {
  if [ -n "$DISPLAY" ] && [ $(which wsname) ]; then
    local name
    name="$(wsname -p)" || return 1
    case $name in
      home|temp|chat|nodes|mail|dash|NSP)
        return 0
        ;;
      emacs)
        cd ~/.emacs.d
        ;;
      www|share)
        cd ~/Downloads
        ;;
      *)
        _z "${HOME}" "${name//-/ }"
        # TODO: maybe modify CDPATH variable
        ;;
    esac
  fi
}

# cd to subdirectory with selection
jd() {
  local query="$@"
  local root=$(command git rev-parse --show-toplevel 2>/dev/null)
  local dir=""
  dir=$(cd "$root" >/dev/null; __select_subdir "$query") || return 1
  cd "${root}${dir}" >/dev/null
}

_find_repos() {
  find -L . -maxdepth 10 \
       -type d -name '.git' -o \
       -type d -name '.hg' \
       2>/dev/null |
    xargs -n 1 dirname 2>/dev/null
}

_jump_repo() {
  local basedir="${1}"
  shift
  [[ -d "${basedir}" ]] || return 1
  local query="$@"
  local selected=$(cd "${basedir}" && _find_repos | cut -c3- | sort |
                        selectline --query="$query") || return 1
  local target="${basedir}/${selected}"
  target=`resolvelink $target`
  cd "$target"
}

# Jump to repository
jr() {
  _jump_repo "${HOME}/src" "$@"
}

# Jump to repository under gopath
jg() {
  _jump_repo "${GOPATH}/src" "$@"
}

# fkill - kill process
# fkill() {
#   ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9}
# }

fkill() {
  ps -h -U $UID -o pid,user,cmd |
    sed -e "s:${HOME}:\~:g" |
    fzf -e -n 3..  |
    sed -e 's/ *\([0-9]* \).*/\1/' |
    xargs kill
}

_lsof_ps_like_common_dev_ports() {
  local c=-1
  local pids
  local names
  local line
  while read -r line
  do
    case $line in
      n*)
        names[pids[c]]+=${line:1}" "
        ;;
      p*)
        pids[++c]=${line:1}
        ;;
    esac
  done < <(lsof -F pcn -iTCP:8000-9000 -sTCP:LISTEN)
  for ((i=0; i<=c; i++))
  do
    for name in ${names[pids[i]]}
    do
      echo "${pids[i]} $(ps -h -o user ${pids[i]}) $name $(ps -h -o cmd ${pids[i]})"
    done
  done
}

fkillport() {
  _lsof_ps_like_common_dev_ports | fzf -e -n 3..  | sed -e 's/ *\([0-9]* \).*/\1/' | xargs kill
}

fpip() {
  local pipfile
  pipfile=$(find \
              -type f -iname requirements\* -o \
              -type f -iwholename \*requirements/\*.txt -o\
              -type f -iwholename \*requirements/\*.pip |
               fzf)
  [[ -z $pipfile ]] && return 1
  pip install -r $pipfile
}

# ftags - search ctags
ftags() {
  local line
  [ -e tags ] &&
    line=$(
      awk 'BEGIN { FS="\t" } !/^!/ {print toupper($4)"\t"$1"\t"$2"\t"$3}' tags |
        cut -c1-80 | fzf --nth=1,2
        ) && $EDITOR $(cut -f3 <<< "$line") -c "set nocst" \
                     -c "silent tag $(cut -f2 <<< "$line")"
}

# fco - checkout git commit
fco() {
  local commits commit
  commits=$(git log --pretty=oneline --abbrev-commit --reverse) &&
    commit=$(echo "$commits" | fzf +s +m -e) &&
    git checkout $(echo "$commit" | sed "s/ .*//")
}

# cd to repository root
cdr() {
  local dir="$(command git rev-parse --show-toplevel)" && builtin cd "$dir"
}
alias ur="cdr"

z() {
  if [[ -z "$*" ]]; then
    cd "$(_z -l 2>&1 | sed -n 's/^[ 0-9.,]*//p' | fzf)"
  else
    case $1 in
      s)
        cd "${HOME}/src"
        ;;
      g)
        cd "${HOME}/src/github.com"
        ;;

      d)
        cd "${HOME}/Downloads"
        ;;

      n)
        cd "${HOME}/notes"
        ;;

      2)
        cd "${HOME}/src/gitlab.23c.se"
        ;;

      *)
        _last_z_args="$@"
        _z "$@"
        ;;
    esac
  fi
}

zz() {
  cd "$(_z -l 2>&1 | sed -n 's/^[ 0-9.,]*//p' | fzf -q $_last_z_args)"
}

alias j=z
alias jj=zz

alias g="git"

# git "update"
gu() {
  command git rev-parse 2> /dev/null || return 1
  command git fetch --all
  command git fetch --tags
  command git rebase
}

# Git "put"
gp() {
  command git rev-parse 2> /dev/null || return 1
  command git push --tags
  command git push
}

s() {
  if command git rev-parse 2> /dev/null; then
    command git status --short --branch
  else
    lsnew 3
  fi
}

gr() {
  command git rev-parse 2> /dev/null || return 1
  command git remote -v
}

# Git fetch all
gf() {
  command git rev-parse 2> /dev/null || return 1
  command git fetch --all
  command git fetch --tags
}

d() {
  command git rev-parse 2> /dev/null || return 1
  command git diff "$@"
}

lg() {
  command git rev-parse 2> /dev/null || return 1
  command git lg "$@"
}

lgv() {
  command git rev-parse 2> /dev/null || return 1
  command git lgv "$@"
}

lgs() {
  command git rev-parse 2> /dev/null || return 1
  command git lgs "$@"
}

lgt() {
  command git rev-parse 2> /dev/null || return 1
  command git lgt "$@"
}

case $HOST_TAGS in
  *:minimalshell:*)
  # nothing
  ;;
  *)
    man() {
      command man "$@" >/dev/null || return $?
      emacs -q -nw -eval "(progn (setq Man-notify-method 'bully) (man \"$@\"))"
    }
    
    ;;
esac


# Go to currently active buffer directory in Emacs
je() {
  local EMACS_CWP=$(emacsclient -a false -e "
  (let ((current-buffer
         (nth 1 (assoc 'buffer-list
                       (nth 1 (nth 1 (current-frame-configuration)))))))
        (with-current-buffer current-buffer
          (let ((filename (buffer-file-name)))
            (if filename
                (file-name-directory filename)
              default-directory))))
    " | sed 's/^"\(.*\)"$/\1/')
  if [ -d "$EMACS_CWP" ]; then
    cd "$EMACS_CWP"
  else
    return 1
  fi
}
alias cdb='je'

pwdclip() {
  pwd | xsel --clipboard
}

__select_ssh() {
  echo -n $(cat ~/.ssh/config | grep ^Host | awk '{ print $2 }' | fzf)
}
export -f __select_ssh

sshc() {
  ssh "$(__select_ssh)"
}

moshc() {
  mosh "$(__select_ssh)"
}

# # TODO WIP
# fontadjust() {
#   local cw="$(tput cols)"
#   local newsize=${__afs_fs}
#   [[ ${cw} != ${__afs_cw} ]] || return 0
#   if [[ ${cw} -lt 60  ]] ; then
#     newsize="9.8"
#   elif  [[ ${cw} -gt 77  ]] ; then
#     newsize="11.8"
#   fi

#   if [[ ${__afs_fs} == ${newsize} ]]; then
#     export __afs_cw="${cw}"
#     return 0
#   fi
#   local font="xft:PragmataPro:size=${newsize}"
#   echo -en "\033]50;$font\007"
#   export __afs_fs="${newsize}"
#   export __afs_cw="${cw}"
# }
