#!/bin/sh
set -e
set -x

dl() {
  curl -s -k -L "${2}" -o "${1}"
}

dl_bin() {
  local dest="${HOME}/.bin/${1}"
  dl "${dest}" "${2}"
  chmod 775 "${dest}"
}

dl_completion() {
  dl "completion.d/${1}" "${2}"
}

dl_completion "nvm" "https://raw.github.com/creationix/nvm/master/bash_completion" &
dl_completion "lein" "https://raw.github.com/technomancy/leiningen/master/bash_completion.bash" &
dl_completion "android" "https://raw.github.com/mbrubeck/android-completion/master/android" &
dl_completion "git" "https://raw.github.com/git/git/master/contrib/completion/git-completion.bash" &
dl_completion "ipython" "https://github.com/ipython/ipython/raw/master/examples/IPython%20Kernel/ipython-completion.bash" &
dl_completion "maven" "https://raw.github.com/juven/maven-bash-completion/master/bash_completion.bash" &
dl_completion "vagrant" "https://raw.github.com/kura/vagrant-bash-completion/master/etc/bash_completion.d/vagrant" &
dl_completion "docker" "https://raw.github.com/dotcloud/docker/master/contrib/completion/bash/docker" &
dl_completion "go" "https://raw.githubusercontent.com/thomasf/go-bash-completion/master/go-bash-completion.bash" &
dl_completion "docker-compose" "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose" &

dl_bin "git-imerge" "https://raw.github.com/mhagger/git-imerge/master/git-imerge" &
dl_bin "git-when-merged" "https://raw.githubusercontent.com/mhagger/git-when-merged/master/bin/git-when-merged" &
dl_bin "ghi" "https://raw.github.com/stephencelis/ghi/master/ghi" &
dl_bin "vcprompt" "https://raw.github.com/djl/vcprompt/master/bin/vcprompt" &
# dl_bin "svtget" "https://raw.github.com/mmn/svtget/master/bash/svtget"
dl_bin "fzf" "https://raw.gitub.com/junegunn/fzf/master/fzf" &
dl_bin "spark" "https://raw.github.com/holman/spark/master/spark" &
# dl_bin "pamixer" "https://raw.github.com/mk-fg/pulseaudio-mixer-cli/master/pulseaudio-mixer-cli.py"
dl_bin "pamixer" "https://raw.github.com/mk-fg/pulseaudio-mixer-cli/master/pa-mixer-mk2.py" &
dl_bin "git-ls-dir" "https://raw.github.com/aspiers/git-config/master/bin/git-ls-dir" &
dl_bin "recollfs" "https://raw.githubusercontent.com/pidlug/recollfs/master/recollfs" &

dl "z" "https://raw.github.com/rupa/z/master/z.sh" &
