#!bash
#
# This file might be sourced during installation with hsadmin
#

[ -e "${HOME}/.config/gitu" ] \
    || ln -fs "$(pwd)/.config-base/gitu" "${HOME}/.config/"

[ -e "${HOME}/.config/pep8" ] \
    || ln -fs "$(pwd)/.config-base/pep8" "${HOME}/.config/"

[ -e "${HOME}/.config/flake8" ] \
    || ln -fs "$(pwd)/.config-base/flake8" "${HOME}/.config/"

[ -e "${HOME}/.pulse/default.pa" ] \
    || (mkdir -p "${HOME}/.pulse" \
    && ln -fs "$(pwd)/.config-base/pulse/default.pa" "${HOME}/.pulse/" )

[ -e "${HOME}/.config/pudb" ] \
    || ln -fs "$(pwd)/.config-base/pudb" "${HOME}/.config/pudb"

gc() {
  git config --global "$@" || true
}
gu() {
  git config --global --unset "$@" || true
}

 case "${USER}" in
   t|thomasf|a00001)
     gc user.name "Thomas Frössman"
     gc user.email "thomasf@jossystem.se"
     gc github.user thomasf
     ;;
 esac


# git config: core/git contrib
 
gc advice.commitbeforemerge false
gc advice.detachedhead false
gc advice.implicitidentity false
gc advice.pushnonfastforward false
gc advice.resolveconflict false
gc advice.statushints false
gc branch.autosetuprebase always
gc branch.sort -committerdate
gc color.ui auto
gc column.ui auto
gc commit.verbose true
gc core.autocrlf input
gc core.editor ee
gc core.excludesfile ~/.gitignore_global
gc core.fsmonitor true
gc core.untrackedCache true
gc diff.algorithm histogram
gc diff.colorMoved plain
gc diff.mnemonicPrefix true
gc diff.renamelimit 50000
gc diff.renames true
gc fetch.all true
gc fetch.prune true
gc fetch.pruneTags true
gc format.pretty "format:%C(yellow)%h%Creset %C(green)%ad%Creset %C(cyan)%ae%Creset %s"
gc help.autocorrect prompt
gc init.defaultBranch master
gc merge.conflictstyle zdiff3
gc mergetool.keepbackup false
gc mergetool.keeptemporaries false
gc mergetool.prompt true
gc pull.rebase true
gc push.autoSetupRemote true
gc push.default upstream
gc rebase.autoSquash true
gc rebase.autoStash true
gc rebase.updateRefs true
gc rerere.autoupdate true
gc rerere.enabled true
gc tag.sort version:refname
gc log.mailmap true

# git config: aliases
gc alias.b "for-each-ref --sort=committerdate refs/heads/ --format='%(align:18)%(color:green)%(committerdate:relative)%(color:reset)%(end)%(color:cyan)%(align:18)%(authorname)%(end)%(color:reset) %(color:yellow)%(refname:short)%(color:reset) %(color:blue)-%(color:reset) %(contents:subject)'"
gc alias.diffdir "difftool -t kdiff3 --dir-diff"
gc alias.lg "log --date=relative --ignore-space-change --stat --pretty=format:'%C(yellow)%h%Creset %C(green)%ad%Creset %C(cyan)%aE% Creset %C(blue)%s%Creset'"
gc alias.lgs "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%aN>%Creset' --abbrev-commit --date=relative"
gc alias.lgt "log --graph --all --pretty=format:'%C(yellow)%h%Creset %C(cyan)%aE%Creset %Cgreen%cr%Creset %s%C(yellow)%d%Creset' --abbrev-commit"
gc alias.lgv "log -p --pretty=format:'%C(yellow)%h%Creset %C(cyan)%aN <%aE>%Creset %Cgreen%cr%Creset %C(magenta)%s%Creset%C(yellow)%d%Creset'"
gc alias.showroot "rev-parse --show-toplevel"
gc alias.staged "diff --cached"
gc alias.verref "describe --tag HEAD"

# git config: third party tools

gc ghq.root "${HOME}/src"
gc hub.autoUpdate "never"

# git config: unset previosly used settings (for migration purposes)

# gc alias.catchup "log --patch --reverse --topo-order _ribbon..origin/master"
# gc alias.ps "push"
# gc alias.pu "pull"
# gc alias.ribbon "tag --force _ribbon origin/master"
# gc log.date "relative"
# gc url.ssh://git@github.com/.insteadOf https://github.com/

gu alias.catchup
gu alias.ps
gu alias.pu
gu alias.ribbon
gu log.date
gu url.ssh://git@github.com/.insteadOf

unset -f gc
unset -f gu
