#!/bin/sh

# Just a small script to install for a bunch of os/platform targets at once

what="${@:-std}"

for os in linux darwin windows; do
  for arch in amd64 386; do
    echo "installing $os-$arch..."
    GOOS=${os} GOARCH=${arch} go install ${what}
  done
done

echo "installing linux-arm7..."
GOARCH=arm GOARM=7 GOOS=linux go install ${what}

echo "installing default..."
go install ${what}
