#!/bin/sh

set -e

path_remove ()  {
  export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`;
}

cmd=$(basename ${0})
[ "$cmd" = "default-python" ] && cmd="python"
if [ -x ~/.virtualenvs/default/bin/$cmd ]; then
    exec ~/.virtualenvs/default/bin/$cmd "$@"
else
  path_remove $(dirname $0)
  exec $cmd "$@"
fi

