#!/bin/bash

# docker logs convinience script that reattaches on container restarts

FZF_DOCKER_PS_FORMAT="table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Ports}}"
if [ $# -eq 0 ]
then
  container=$(docker ps --format "${FZF_DOCKER_PS_FORMAT}" | fzf --header-lines=1 --bind 'enter:execute(echo {2})+abort')
else
  container="${1}"
fi
[[ -z "$container" ]] && return
hr
hr
hr
args="--tail 2000"
while true; do
  container_id=$(docker ps -f name="${container}" -q)
  if [[ -n "$container_id" ]]; then
    hr
    docker logs -f ${args} "${container}"
  fi
  args="--tail 0"
  sleep 0.1
done
