#!/bin/bash
# set -x
C="${1}"
LEN="${2:-80}"
export LC_ALL=C
set -eu
rnd() {
  local cutset="${1}"
  if [ -e /dev/urandom ]; then
    tr -dc "${cutset}" </dev/urandom | head -c ${LEN}
  elif hash openssl 2>/dev/null; then
    openssl rand 1024  | tr -dc "${cutset}" | fold -w ${LEN} | head -n 1
  else
    echo "no way to generate a random number"
    exit 1
  fi
  echo
}
# test: echo $(for n in $(seq 1 100); do generate-password an; done) |  grep -o . | sort  | uniq | tr -d "\n"
case $C in
  h|-h) # print help/source
    cat ${0}
    ;;
  c|complex) # lots of entropy
    rnd  'A-Za-z0-9!"#$%&'\''()*+,\-./:;<=>?@[\]^_`{|}~'
    ;;
  an|alphanumeric) #
    rnd 'a-zA-Z0-9'
    ;;
  *|s|safe) # shell safe and safe from common separators
    rnd 'A-Za-z0-9+\-@^_{}'
    ;;
esac
