#!/bin/sh
#
# Show age of all files in under current directory in a sortable way.
#

set -e

VERSION="2"

SUBDIRECTORY_OK=Yes
OPTIONS_KEEPDASHDASH=""
OPTIONS_SPEC="\
git age"

version_print() {
    echo "git age version ${VERSION}"
}

git ls-files | xargs -n1 -i{} git log -1 --pretty=format:"%ci {}%n" -- {}
