#!/bin/sh
#
# Ensures some things about files and folders
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

if [ -d "${HOME}/.ssh" ]; then
    chmod 700 ~/.ssh
    find ~/.ssh/ -type d -exec chmod 700 {} +
    find ~/.ssh/ -type f -exec chmod 600 {} +
    find ~/.ssh/ -maxdepth 1 -name "*.pub" -exec chmod 644 {} +
fi

# Secure .gnupg directory
if [ -d "${HOME}/.gnupg" ]; then
  chmod 700 ~/.gnupg
  find ~/.gnupg/ -type d -exec chmod 700 {} +
  find ~/.gnupg/ -type f -exec chmod 600 {} +
fi

# If option o is given, take ownership of some directories
# that might have files accidently owned by root while sudoing.
if  [ "${1}" = "o" ]; then
  [ -d "${HOME}/.venvburrito" ] && sudo chown -R ${USER} "${HOME}/.venvburrito"
  [ -d "${HOME}/.virtualenvs" ] && sudo chown -R ${USER} "${HOME}/.virtualenvs"
  # Node version manager
  [ -d "${HOME}/.nvm" ] && sudo chown -R ${USER} "${HOME}/.nvm"
  # Ruby version manager
  [ -d "${HOME}/.rvm" ] && sudo chown -R ${USER} "${HOME}/.rvm"
  # Haskell/Cabal
  [ -d "${HOME}/.cabal" ] && sudo chown -R ${USER} "${HOME}/.cabal"
  [ -d "${HOME}/.ghc" ] && sudo chown -R ${USER} "${HOME}/.ghc"
  # emacs
  [ -d "${HOME}/.emacs.d" ] && sudo chown -R ${USER} "${HOME}/.emacs.d"

fi
