#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""
pretty ls

Author: Thomas Frössman
"""
from subprocess import PIPE, Popen
import re
from sys import argv
from platform import platform

p = re.compile("^([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+\s+[^\s]+\s+[^\s]+) (.*)")  # noqa

command = ['ls',  '-lhtr']
if platform(terse=True).startswith("Darwin"):
    command += ['-G']
else:
    command += ['--color', '--group-directories-first']
command += argv[1:]

process = Popen(command, stdout=PIPE)

while True:
    line = process.stdout.readline().decode('utf8')
    if line != '':
        if p.match(line):
            m = p.search(line)
            # print line.rstrip(), m.group(1)
            date = m.group(6)
            size = m.group(5)
            rest = m.group(7)
            print u"%14s %6s %s" % (date, size, rest)
        else:
            print line.rstrip()
    else:
        break
