#!/bin/bash

set -e
# set -x

py_v="3"
cmd="NO_COMMAND"
bn=$(basename ${0})
env_name=${bn}


# colors
reset="$(tput sgr0 2>/dev/null||echo -n)"
red="$(tput setaf 1 2>/dev/null||echo -n)"
green="$(tput setaf 2  2>/dev/null||echo -n)"
yellow="$(tput setaf 3  2>/dev/null||echo -n)"
magenta="$(tput setaf 5  2>/dev/null||echo -n)"


ts() {
  echo "${reset}[$(date +%T)] ${@}"
}


upgrade-env() {
  local env_dir=${1}
  ts "$yellow ->  $magenta $env_dir $reset"
  deactivate 2> /dev/null|| true
  echo -n ${env_name} | (
    set -e &&
    cd "${env_dir}" &&
    . bin/activate &&
    pip install --upgrade -r requirements.txt
  )
  ts "$yellow <- $magenta $env_dir $reset"
}

list-envs() {
  find ${HOME}/.virtualenvs-cmd/  -maxdepth 1 -mindepth 1 -type d
}



upgradeall() {
  deactivate || true
  for d in ${HOME}/.virtualenvs-cmd/*; do
    export d
    (
      set -e
      cd ${d}
      . bin/activate
      pip install --upgrade $(cat requirements.txt)
    )
  done
}

case ${bn} in
  py-cmd-env)
    subcommand=${1}
    shift
    case ${subcommand} in
      u|upgrade)
        upgradeall
        exit 0
        ;;
      ls|list-envs)
        list-envs
        exit 0
        ;;
      upgrade-env)
        upgrade-env "$1"
        exit 0
        ;;
    esac
    echo "usage ${0} upgrade"
    exit 1
    ;;
  glfs)
    packages=gitlabfs
    env_name=gitlabfs
    ;;
  pre-commit|pre-commit-validate-manifest|pre-commit-validate-config)
    packages=pre-commit
    env_name=pre-commit
    ;;
  ansible|ansible-playbook|ansible-config|ansible-connection|ansible-console|ansible-doc|ansible-galaxy|ansible-inventory|ansible-pull|ansible-vault)
    packages=ansible
    env_name=ansible
    ;;
  platformio|pio)
    py_v="2"
    packages=platformio
    env_name=platformio
    ;;
  git-goggles)
    py_v="2"
    packages="git-goggles termcolor"
    ;;
  youtube-dl)
    packages=youtube_dl
    ;;
  devpi)
    packages=devpi-client
    ;;
  gitlab)
    packages=python-gitlab
    ;;
  dephell)
    packages="dephell[full]"
    ;;
  *)
    packages=${bn}
    ;;
esac


envs_root="${HOME}/.virtualenvs-cmd"
env_path="${envs_root}/${env_name}"
cmd_path="${env_path}/bin/${bn}"

if [ ! -e "${cmd_path}" ]; then
  deactivate 2>/dev/null || true
  mkdir -p ${envs_root}
  case ${py_v} in
    3*)
      python3 -mvenv --clear "${env_path}"
      ;;
    2*)
      virtualenv -p python2 "${env_path}"
      ;;
    *)
      echo "Nothing to do for ${py_v}"
      exit 1
      ;;
  esac

  ${env_path}/bin/pip install wheel
  ${env_path}/bin/pip install ${packages}
  echo ${packages} > "${env_path}/requirements.txt"
fi

exec ${cmd_path} "$@"
