#!/bin/sh

if [ `which pt` ]; then
    ptargs='--context=0 --color --ignore=node_modules  --ignore=vendor --ignore=Godeps'
    pt $ptargs -e TODO[:]? | tr \\t ' ' | tr -s [:blank:]
    pt $ptargs -e FIXME[:]? | tr \\t ' ' | tr -s [:blank:]
else
    ackargs="--color --group"
    ack $ackargs --color-match="yellow" TODO | tr \\t ' ' | tr -s [:blank:]
    ack $ackargs --color-match="magenta" FIXME | tr \\t ' ' | tr -s [:blank:]
fi
