#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Serves content for current directory
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

import sys
import BaseHTTPServer
from SimpleHTTPServer import SimpleHTTPRequestHandler
import socket

port_range_start = 8500
port_range_end = 8600

HandlerClass = SimpleHTTPRequestHandler
ServerClass  = BaseHTTPServer.HTTPServer
Protocol     = "HTTP/1.0"
#Host = '127.0.0.1'
Host = '0.0.0.0'

if sys.argv[1:]:
    port = int(sys.argv[1])
    port_range_start=port
    port_range_end=port

connected=False
port=port_range_start

httpd = None
HandlerClass.protocol_version = Protocol

while (not connected and port <= port_range_end):
    try:
        server_address = (Host, port)
        httpd = ServerClass(server_address, HandlerClass)
        connected=True
    except socket.error,e:
        if port is port_range_end:
            print "port " + str(port) + " is already bound, trying +1"
        else:
            print "port " + str(port) + " is already bound, exitting"
        port=port+1

sa = httpd.socket.getsockname()
print "Serving HTTP on", sa[0], "port", sa[1], "..."

httpd.serve_forever()
