#!/bin/bash
#
#

set -e
set -x


# cdo cd's into ~/.opt/$1
cdo() {
  cd "${HOME}/.opt/${1}"
}
export -f cdo

# uptodate fetches a git repo and returns non 0 if HEAD is in sync with remote.
uptodate() {
  local dir=${1}
  [ ! -d ${dir} ] && return 0
  cd ${dir}
  git fetch upstream master
  local changes=$(git rev-list HEAD..upstream/master --count)
  echo "uptodate ${dir} changes: ${changes}"
  return $changes
  # return 2
}
export -f uptodate

# resetupstream resets a git working tree
resetupstream() {
  git log HEAD..upstream/master --oneline
  git reset --hard upstream/master
}
export -f resetupstream

# runCmd runs a command in a subshell, on graphical terminals this
runCmd() {
  if [ -n "$DISPLAY" ] && [ `which urxvt` ]; then
    exec urxvt -title upgradeall -name upgradeall -e bash -c \
         "termcolors; echo RUN \" $* \";
$*
echo ;
echo \"COMPLETED: $* \";
echo \">>> ENTER KEY CLOSES TERMINAL!\";
read any;" &
  else
    (
      set +e
      $*
    )
  fi
}

# runcmdifchange runs a command in a subshell if there are changes in the
# remote git repo
runCmdIfChange() {
  local dir=${1}
  local cmd=${2}
  uptodate "${HOME}/.opt/${dir}" || runCmd "${0} ${cmd}"
}
export -f runCmdIfChange

# upgrader-goget installs variout things using go get.
upgrader-goget() {
  (
  echo UPDATING yt-download
  youtube-dl --update
  ) &
  echo UPDATING go-tools
  GOPATH=~/repos/go
  export GOPATH;
  go get -v -u \
     code.google.com/p/rog-go/exp/cmd/godef \
     github.com/golang/lint/golint \
     github.com/junegunn/fzf/src/fzf \
     github.com/nsf/gocode \
     github.com/laher/goxc \
     github.com/shurcooL/markdownfmt \
     github.com/tools/godep \
     golang.org/x/tools/cmd/eg \
     golang.org/x/tools/cmd/goimports \
     golang.org/x/tools/cmd/gorename \
     golang.org/x/tools/cmd/oracle \
     golang.org/x/tools/cmd/vet \
     github.com/github/hub \
     github.com/jstemmer/gotags \
  ;

  # github.com/monochromegane/the_platinum_searcher/... \
}

upgrader-dunst() {
  cdo dunst
  resetupstream
  make
  sudo make install
}

upgrader-compton(){
  cdo compton
  resetupstream
  make
}

upgrader-mu(){
  cdo mu
  resetupstream
  make
  sudo make install
}

upgrader-npm() {
  npm install -g \
      npm-proxy-cache \
      bower \
      browserify watchify \
      coffee-script \
      coffeelint \
      docco \
      grunt-cli \
      gulp \
      js2coffee \
      jshint \
      jslint \
      jsonlint \
      stylus \
      titanium \
      uglify-js \
      uglifycss \
      underscore-cli \
      webpack \
      jsxhint \
      tern
}

cmd=${1}
case $cmd in
  goget|dust|compton|mu|npm)
    upgrader-${cmd}
    ;;
  *)
    runCmdIfChange "${HOME}/.opt/dunst" "dunst" &
    runCmdIfChange "${HOME}/.opt/compton" "compton" &
    runCmdIfChange "${HOME}/.opt/mu" "mu" &
    runCmd "sudo apt-get update ; sudo apt-get dist-upgrade"
    runCmd "xmonadUpdate"
    runCmd "${HOME}/.emacs.d/installDeps emacs"
    runCmd "hsadmin pull"
    runCmd "$0 goget" &
    ;;
esac

