#!/bin/sh

cmd=$(basename ${0})
runcmd="${@}"

case $cmd in
  watchgo)
    lookfor="go h c m"
    ;;
  watchdjangotest)
    lookfor="py"
    runcmd="pyrg manage.py test ${@}"
    ;;
  *)
    lookfor="$1"
    shift
    ;;
esac

while file=$(inotifywait -q -r -e modify --format "%w%f" ./); do
  EXT=${file##*.}
  for check in $lookfor; do
    if [ $EXT = $check ]; then
      eval ${runcmd}
      echo -n "*"
      continue
    fi
  done
done
