#!/usr/bin/env bash
if [ -r "${rvm_scripts_path:-$rvm_path/scripts}/extras/completion.bash" ]; then
  source "${rvm_scripts_path:-$rvm_path/scripts}/extras/completion.bash"
  complete -o default -o nospace -F _rvm rvm
fi
